### ISSUE TITLE
Hello, I am interested with this project. How I can help?

### ISSUE THREAD

**Issue by rubiagatra** [bloom42/signal#2]
Hello, my name is Doni, I am from Indonesia.
My day job as a back-end engineer and mainly using Go.

I hope somehow I could help this project. 

Thank you

**Comment by z0mbie42** [comment]
Hi, thank you very much for your interest!

I think an interesting next step would be to display users in real time in the dashboard (x current visitors).

As I have not yet a clear on how to implement this feature I have opened #3

A Good start would be to discuss what implementations are possible, and pick the best
