### ISSUE TITLE
logging update

### ISSUE THREAD

**Issue by gedw99** [bloom42/signal#5]
are you planning to use the new logger?

Currently this project uses:
github.com/bloom42/astroflow-go

**Comment by z0mbie42** [comment]
Hi, thank your for reaching.

Unfortunately this project is deprecated in favor of a far better one I'm working on that will be open sourced in the next few month (more than 1000x better ;). So there is no plan to update this and it will be marked as archived soon.

OTHO  bloom42/astroflow-go is now https://github.com/bloom42/rz-go but the API is not fully stable (I'm currently working actively on this) so it's preferable to not use it in production until some days.
